name: flutter_hbys
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_plugin_baseframwork:
    # When depending on this package from a real application you should use:
    #   flutter_plugin_baseframwork: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: plugins/flutter_plugin_baseframwork
  xf_speech_plugin:
    path: plugins/xfspeech_plugin-master
  rongcloud_im_plugin:
    path: plugins/rongcloud-im-flutter-sdk-master

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

    #实现国际化的配置
  flutter_localizations:
      sdk: flutter

  dio: ^3.0.10 #网络请求插件
  package_info: ^0.4.3 #包信息
  json_serializable: ^3.5.0
  connectivity: ^2.0.0 #监听网络连接方式的插件
  oktoast: ^2.3.2 #吐司插件
  common_utils: ^1.2.1
  shared_preferences: ^0.5.12+4
#  rongcloud_im_plugin: ^4.0.3 #融云sdk
  flutter_plugin_record: ^0.3.4 #仿微信录音的插件
  fbutton: ^2.0.1
  flustars: ^0.3.3 #Flutter常用工具类库
  fluttertoast: ^7.1.1
  image_gallery_saver: ^1.2.2
  flutter_cache_manager: ^1.2.0
#  percent_indicator: ^2.1.2
  video_player: ^0.10.2+3
  camera: ^0.5.5+1
  permission_handler: ^5.0.0+hotfix.3
  open_file: ^3.0.1
  flutter_webview_plugin: ^0.3.11
  url_launcher: ^5.4.2
  flutter_sound: ^2.1.1
  flutter_audio_recorder: ^0.5.5
  image_picker: ^0.6.0+20
  file_picker: ^1.4.3+2
  percent_indicator: ^2.1.8
dev_dependencies:

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
    enabled: true

